spring:
  application:
    name: FRAMEWORK-GENERATOR

app:
  rest:
    base-url: http://localhost:8080

project:
  groupId: com.example
  version: 1.0.0
  modules:
    - name: module-a
      dependencies:
        - web
        - thymeleaf
    - name: module-b
      dependencies:
        - data-jpa
        - mysql